### ISSUE TITLE
Fixed to work on current love2d framework

### ISSUE THREAD

**Issue by alejandro-alzate** [ortzinator/solitaire#1]
Was suspiciously easy:
modified all `card.lua` draw calls from `love.graphics.drawq()` to `love.graphics.draw()`
modified all `conf.lua` window references from `screen` to `window`

I was seeking for just the solitarie logic; thank you, also getting the pr achievement but oh well.

Take the fix if you like: https://github.com/alejandro-alzate/solitaire-lua-fixed

Working as May 1 2023

**Comment by ortzinator** [comment]
Awesome! Thank you!

**Comment by alejandro-alzate** [comment]
No problem the fix was simple but hidden, Spotting it and not helping would be a crime
